### PR TITLE
fix setup.py import

### PR DESCRIPTION
**Pull request by pdufour**
@britco/owners fixes the error with this command

```
pip install git+https://github.com/britco/django-oscar-amazon-payments.git@0.0.2
```

```
You are using pip version 6.0.8, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting git+https://github.com/britco/django-oscar-amazon-payments.git@0.0.2
  Cloning https://github.com/britco/django-oscar-amazon-payments.git (to 0.0.2) to /var/folders/f8/../T/pip-rWXpJ8-build
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/f8/5b5/T/pip-rW-build/setup.py", line 4, in <module>
        from amazon_payments import VERSION
      File "amazon_payments/__init__.py", line 1, in <module>
        from api import AmazonPaymentsAPI, AmazonPaymentsAPIError  # noqa
      File "amazon_payments/api.py", line 10, in <module>
        import requests
    ImportError: No module named requests
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/var/folders/f8/5b5/T/pip-rW-build/setup.py", line 4, in <module>

        from amazon_payments import VERSION

      File "amazon_payments/__init__.py", line 1, in <module>

        from api import AmazonPaymentsAPI, AmazonPaymentsAPIError  # noqa

      File "amazon_payments/api.py", line 10, in <module>

        import requests

    ImportError: No module named requests

    ----------------------------------------
```

Caused by importing `requests` before `requests` is installed. Changed version import to use same method as requests lib: https://github.com/kennethreitz/requests/blob/1145fe/setup.py#L31-L42

### CODE REVIEW

**Comment by monokrome** [comment]
@pdufour Good find. Instead of this, though, it reveals that we are having an issue with Python 2's import resolution. If we revert to the old code and then convert the import to `from .amazon_payments import VERSION` then we should be in good shape.

The `.` will force it to be a relative import instead of grabbing the global package. :)

**Comment by pdufour** [comment]
@monokrome Re: our talk, I'd rather fix it this way because it fixes the problem with very minor impact. It also seems like a pattern other libraries implemented (see requests link).

This is the condition we are seeing:
http://stackoverflow.com/a/2073599

> Warning about race condition during install
> 
> By the way, DO NOT import your package from your setup.py as suggested in another answer here: it will seem to work for you (because you already have your package's dependencies installed), but it will wreak havoc upon new users of your package, as they will not be able to install your package without manually installing the dependencies first.

**Comment by monokrome** [comment]
@pdufour What are your thoughts on the alternative solution in https://github.com/britco/django-oscar-amazon-payments/pull/4/?

**Comment by pdufour** [comment]
@monokrome There's a number of ways to do it it, so we just have to choose one. I think we should find a way to do it without catching `ImportError`s though.

**Comment by monokrome** [comment]
@pdufour I don't think that @sjolicoeur's solution catches any import errors, right?

**Pull request closed without merging**
